/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DiskScheduling;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Math.abs;
import javax.accessibility.AccessibleContext;
import javax.swing.JOptionPane;
import java.io.*;
import os_simulator.MainPage;
import javax.swing.ImageIcon;
/**
 *
 * @author GJ
 */
public class launchFrame extends javax.swing.JFrame {

    int ctr = 0;
    static int ARRAY[] = new int[1000];
    static int SORTED_ARRAY[] = new int[1000];
    static int returnArray[] = new int[1000];
    static int END = 0;
    int THM = 0;
    static String DISPLAY;
    int x;
    float ST = 0;
    static int DIRECTION = 0;
    int temp_END = 0;
   
    
    public launchFrame() {  
        for( x = 0;x<1000;x++)
        {
            ARRAY[x] = '\0';
            SORTED_ARRAY[x] = '\0';
        }
        ImageIcon icon = new ImageIcon("rsc\\disk_scheduling.png");
        setIconImage(icon.getImage());
        initComponents();
        fcfsBttn.setSelected(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu3 = new javax.swing.JMenu();
        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        diskSchedLbl = new javax.swing.JLabel();
        scanTypePanel = new javax.swing.JPanel();
        computeBttn = new javax.swing.JButton();
        fcfsBttn = new javax.swing.JRadioButton();
        sstfBttn = new javax.swing.JRadioButton();
        scanBttn = new javax.swing.JRadioButton();
        cScanBttn = new javax.swing.JRadioButton();
        scanTypeLbl = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        trackNoLbl = new javax.swing.JLabel();
        trackNoField = new javax.swing.JTextField();
        currPosField = new javax.swing.JTextField();
        prevPosField = new javax.swing.JTextField();
        dirComboBox = new javax.swing.JComboBox();
        arrayLbl = new javax.swing.JLabel();
        arrayField = new javax.swing.JTextField();
        nextBttn = new javax.swing.JButton();
        prevPosBttn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();
        trackNoLbl1 = new javax.swing.JLabel();
        trackNoLbl2 = new javax.swing.JLabel();
        trackNoLbl3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disk Scheduling Algorithm");
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setName("Disk Scheduling Algorithm"); // NOI18N

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        diskSchedLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        diskSchedLbl.setText("Disk Scheduling Algorithm");

        scanTypePanel.setBackground(new java.awt.Color(204, 204, 204));
        scanTypePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        computeBttn.setBackground(new java.awt.Color(255, 255, 255));
        computeBttn.setFont(diskSchedLbl.getFont());
        computeBttn.setForeground(new java.awt.Color(0, 51, 51));
        computeBttn.setText("Compute");
        computeBttn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        computeBttn.setBorderPainted(false);
        computeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBttnActionPerformed(evt);
            }
        });

        fcfsBttn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(fcfsBttn);
        fcfsBttn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fcfsBttn.setText("First Come First Serve");
        fcfsBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcfsBttnActionPerformed(evt);
            }
        });

        sstfBttn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(sstfBttn);
        sstfBttn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sstfBttn.setText("Shortest Seek Time First");
        sstfBttn.setActionCommand("");
        sstfBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstfBttnActionPerformed(evt);
            }
        });

        scanBttn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(scanBttn);
        scanBttn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scanBttn.setText("SCAN");
        scanBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanBttnActionPerformed(evt);
            }
        });

        cScanBttn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cScanBttn);
        cScanBttn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cScanBttn.setText("C-SCAN");
        cScanBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cScanBttnActionPerformed(evt);
            }
        });

        scanTypeLbl.setBackground(new java.awt.Color(255, 255, 255));
        scanTypeLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        scanTypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scanTypeLbl.setText("Scan Type");
        scanTypeLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        infoPanel.setBackground(new java.awt.Color(204, 204, 204));
        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        trackNoLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        trackNoLbl.setText("No. of tracks:");
        trackNoLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        trackNoField.setFont(trackNoLbl.getFont());
        trackNoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        trackNoField.setText("0");
        trackNoField.setBorder(null);
        trackNoField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        trackNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                trackNoFieldKeyReleased(evt);
            }
        });

        currPosField.setFont(trackNoLbl.getFont());
        currPosField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currPosField.setText("0");
        currPosField.setBorder(null);
        currPosField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                currPosFieldKeyReleased(evt);
            }
        });

        prevPosField.setFont(trackNoLbl.getFont());
        prevPosField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prevPosField.setText("0");
        prevPosField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        prevPosField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prevPosFieldKeyReleased(evt);
            }
        });

        dirComboBox.setFont(diskSchedLbl.getFont());
        dirComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UPWARD", "DOWNWARD" }));
        dirComboBox.setEnabled(false);
        dirComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirComboBoxActionPerformed(evt);
            }
        });

        arrayLbl.setFont(trackNoLbl.getFont());
        arrayLbl.setText("Array ["+ctr+"] value:");

        arrayField.setFont(trackNoLbl.getFont());
        arrayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arrayField.setText("0");
        arrayField.setToolTipText("");
        arrayField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        arrayField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                arrayFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arrayFieldKeyReleased(evt);
            }
        });

        nextBttn.setBackground(new java.awt.Color(255, 255, 255));
        nextBttn.setFont(diskSchedLbl.getFont());
        nextBttn.setForeground(new java.awt.Color(0, 51, 51));
        nextBttn.setText("ADD");
        nextBttn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nextBttn.setBorderPainted(false);
        nextBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBttnActionPerformed(evt);
            }
        });

        prevPosBttn.setBackground(new java.awt.Color(255, 255, 255));
        prevPosBttn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        prevPosBttn.setText("ON");
        prevPosBttn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        prevPosBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevPosBttnActionPerformed(evt);
            }
        });

        Output.setColumns(20);
        Output.setRows(5);
        jScrollPane1.setViewportView(Output);

        trackNoLbl1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        trackNoLbl1.setText("Previous Position");
        trackNoLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        trackNoLbl2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        trackNoLbl2.setText("Current Position");
        trackNoLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        trackNoLbl3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        trackNoLbl3.setText("Direction of R/W head");
        trackNoLbl3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Output");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(trackNoLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dirComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(trackNoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trackNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(arrayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(arrayField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(nextBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trackNoLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prevPosBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prevPosField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(trackNoField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currPosField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trackNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trackNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trackNoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(currPosField)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prevPosField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prevPosBttn)
                        .addComponent(trackNoLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trackNoLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrayLbl)
                    .addComponent(arrayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBttn))
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout scanTypePanelLayout = new javax.swing.GroupLayout(scanTypePanel);
        scanTypePanel.setLayout(scanTypePanelLayout);
        scanTypePanelLayout.setHorizontalGroup(
            scanTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scanTypePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scanTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fcfsBttn)
                    .addComponent(scanBttn)
                    .addComponent(cScanBttn)
                    .addComponent(sstfBttn)
                    .addGroup(scanTypePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(computeBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scanTypePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(scanTypeLbl)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        scanTypePanelLayout.setVerticalGroup(
            scanTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scanTypePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(scanTypeLbl)
                .addGap(18, 18, 18)
                .addComponent(fcfsBttn)
                .addGap(29, 29, 29)
                .addComponent(sstfBttn)
                .addGap(32, 32, 32)
                .addComponent(scanBttn)
                .addGap(26, 26, 26)
                .addComponent(cScanBttn)
                .addGap(18, 18, 18)
                .addComponent(computeBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(scanTypePanelLayout.createSequentialGroup()
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 319, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("<-BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scanTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addGap(108, 108, 108)
                .addComponent(diskSchedLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskSchedLbl)
                    .addComponent(jButton1))
                .addGap(8, 8, 8)
                .addComponent(scanTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevPosBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevPosBttnActionPerformed
        if(prevPosBttn.isSelected())
        {
            dirComboBox.setEnabled(true);
            prevPosField.setEnabled(false);
            prevPosBttn.setText("OFF");
        }
        else
        {
            prevPosBttn.setText("ON");
            prevPosField.setEnabled(true);
            dirComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_prevPosBttnActionPerformed

    private void nextBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBttnActionPerformed
        int SUCCESS = saveValuesToArray();
        if(SUCCESS == 0)
        {

        }
    }//GEN-LAST:event_nextBttnActionPerformed

    private void arrayFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrayFieldKeyReleased
        try
        {
            if(evt.getKeyCode()==10);
            else
            {
                int x = Integer.parseInt(arrayField.getText());
                int y = Integer.parseInt(trackNoField.getText());
                if(((x<0)||(x>=y)))
                {
                    JOptionPane.showMessageDialog(null,"Not in range!","Status:Error",JOptionPane.ERROR_MESSAGE);
                    arrayField.setText("");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Invalid Input!","Status:Error",JOptionPane.ERROR_MESSAGE);
            arrayField.setText("");
        }
    }//GEN-LAST:event_arrayFieldKeyReleased

    private void arrayFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrayFieldKeyPressed
        if(evt.getKeyCode() == 10)
        {
            int SUCCESS = saveValuesToArray();
            if(SUCCESS == 0)
            {

            }
        }
    }//GEN-LAST:event_arrayFieldKeyPressed

    private void prevPosFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prevPosFieldKeyReleased
        try
        {
            int x = Integer.parseInt(prevPosField.getText());
            int y = Integer.parseInt(trackNoField.getText());
            if(evt.getKeyCode()==10);
            else
            if((x>=y)||(x<0))
            {
                prevPosField.setText("");
                JOptionPane.showMessageDialog(null,"Input does not match the range!","Status:Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Invalid Input!","Status:Error",JOptionPane.ERROR_MESSAGE);
            prevPosField.setText("");
        }
    }//GEN-LAST:event_prevPosFieldKeyReleased

    private void currPosFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currPosFieldKeyReleased
        try
        {
            int x = Integer.parseInt(currPosField.getText());
            int y = Integer.parseInt(trackNoField.getText());
            if(evt.getKeyCode()==10);
            else
            if((x>=y)||(x<0))
            {
                currPosField.setText("");
                JOptionPane.showMessageDialog(null,"Input does not match the range!","Status:Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Invalid Input!","Status:Error",JOptionPane.ERROR_MESSAGE);
            currPosField.setText("");
        }
    }//GEN-LAST:event_currPosFieldKeyReleased

    private void trackNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_trackNoFieldKeyReleased
        try
        {
            int x = Integer.parseInt(trackNoField.getText());
            if(evt.getKeyCode()==10);
            else
            if(x<0)
            {
                JOptionPane.showMessageDialog(null,"Number of tracks must not be negative","Status:Error",JOptionPane.ERROR_MESSAGE);
                trackNoField.setText("");
            }
            else if(END>0)
            {
                sortArray();
                if(x<SORTED_ARRAY[END-1])
                {
                    JOptionPane.showMessageDialog(null,"Track number must not be less than the Array inputted","Status:Error",JOptionPane.ERROR_MESSAGE);
                    trackNoField.setText("");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Invalid Input!","Status:Error",JOptionPane.ERROR_MESSAGE);
            trackNoField.setText("");
        }
    }//GEN-LAST:event_trackNoFieldKeyReleased

    private void cScanBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cScanBttnActionPerformed
        
    }//GEN-LAST:event_cScanBttnActionPerformed

    private void scanBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanBttnActionPerformed
        
    }//GEN-LAST:event_scanBttnActionPerformed

    private void sstfBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstfBttnActionPerformed
       
    }//GEN-LAST:event_sstfBttnActionPerformed

    private void fcfsBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcfsBttnActionPerformed
        
    }//GEN-LAST:event_fcfsBttnActionPerformed

    private void computeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBttnActionPerformed

        END = temp_END;
        try
        {
            if(fcfsBttn.isSelected() == true)
            fcfsProcess();
            else
            {
                sortArray();
                if(cScanBttn.isSelected()==true)
                c_scanProcess();

                if(scanBttn.isSelected() == true)
                scanProcess();

                if(sstfBttn.isSelected()==true)
                sstfProcess();
            }

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_computeBttnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dirComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirComboBoxActionPerformed

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(launchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new launchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Output;
    private javax.swing.JTextField arrayField;
    private javax.swing.JLabel arrayLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JRadioButton cScanBttn;
    private javax.swing.JButton computeBttn;
    private static javax.swing.JTextField currPosField;
    private javax.swing.JComboBox dirComboBox;
    private javax.swing.JLabel diskSchedLbl;
    private static javax.swing.JRadioButton fcfsBttn;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBttn;
    private javax.swing.JPanel panel;
    private javax.swing.JToggleButton prevPosBttn;
    private static javax.swing.JTextField prevPosField;
    private static javax.swing.JRadioButton scanBttn;
    private javax.swing.JLabel scanTypeLbl;
    private javax.swing.JPanel scanTypePanel;
    private static javax.swing.JRadioButton sstfBttn;
    private static javax.swing.JTextField trackNoField;
    private javax.swing.JLabel trackNoLbl;
    private javax.swing.JLabel trackNoLbl1;
    private javax.swing.JLabel trackNoLbl2;
    private javax.swing.JLabel trackNoLbl3;
    // End of variables declaration//GEN-END:variables

    private int saveValuesToArray() {
       int SUCCESS = 0;
       try
       {
           String temp_display;
           int TRACK = Integer.parseInt(trackNoField.getText());
           int NUMBER = Integer.parseInt(arrayField.getText());
           if(TRACK>0)
           temp_display  = "Number not in range! ( 0 to " +(TRACK-1)+" )";
           else
           temp_display  = "Input a number greater than 0!";   
           if((NUMBER>=0)&&(NUMBER<TRACK)){
                ARRAY[ctr] = NUMBER;
                ctr++;
           
                
                END = ctr;
                temp_END = END;

                arrayLbl.setText("Array ["+ctr+"] value:");
                arrayField.setText("");
                
            }
           else
           {
               SUCCESS = 1;
               JOptionPane.showMessageDialog(null,""+temp_display,"Status: Error!",JOptionPane.ERROR_MESSAGE);
           }
       }
       catch(NumberFormatException | HeadlessException e)
       {
           JOptionPane.showMessageDialog(null,"Please input a number!","Status: Error!",JOptionPane.ERROR_MESSAGE);
           SUCCESS = 1;
       }    
       
       return SUCCESS;
    }

    private void fcfsProcess() {
        try
        {
            for(x = 0;x<END;x++)
                returnArray[x]=ARRAY[x];
            THM = 0;
            int TEMP = Integer.parseInt(currPosField.getText());
            int VALUE = TEMP;
            int TRACK = Integer.parseInt(trackNoField.getText());
            DISPLAY = "First Come First Serve\n\n";
 
            for( x = 0;x<END;x++)
            {
                THM+= abs(ARRAY[x]-TEMP);
                TEMP = ARRAY[x];
                Output.append(Integer.toString(TEMP)+" ");
            }
            
            DISPLAY += "Total Head Movement:" + THM + "\n\n";
            Output.append("\nTotal Head Movement:" + THM + "\n\n");
            DISPLAY += "Seek Time:" + ST +"ms\n\n";
       }
       catch(Exception e)
       {
            e.printStackTrace();}
       }  

    private void sortArray() {
        try
        {
            int same_number_ctr = 0;
            int currPos = Integer.parseInt(currPosField.getText());            
            
            for(x = 0;x<END;x++)
            {
                SORTED_ARRAY[x] = ARRAY[x];
            }
            
            for(x = 0;x+same_number_ctr<END;x++)
            {
                if(currPos==SORTED_ARRAY[x])same_number_ctr++;
                SORTED_ARRAY[x] = SORTED_ARRAY[x+same_number_ctr];
            }
                temp_END = END;
                END-=same_number_ctr;
                
            for(x = 0;x<END-1;x++)
                for(int y = 0;y<END-1;y++)
                    if(SORTED_ARRAY[y]>SORTED_ARRAY[y+1])
                    {
                        int TEMP = SORTED_ARRAY[y];
                        SORTED_ARRAY[y] = SORTED_ARRAY[y+1];
                        SORTED_ARRAY[y+1] = TEMP;
                    }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    private void c_scanProcess() {
        try
        {
            int highestValue = Integer.parseInt(trackNoField.getText())-1;
            int prevPos = Integer.parseInt(prevPosField.getText());
            int currPos = Integer.parseInt(currPosField.getText());
 
            String direction = "";
            direction += dirComboBox.getSelectedItem();
            String a_string = "";
            DISPLAY = "C-SCAN\n\n";    

            for(x = 0;x<END;x++)
                if((SORTED_ARRAY[x]<currPos)&&(currPos<=SORTED_ARRAY[x+1]))
                        break;

            if(prevPosField.isEnabled() == true)
            {
                if(prevPos<currPos)
                {
                    THM = abs(highestValue-currPos) + abs(SORTED_ARRAY[x]);
                    DIRECTION = 1;
                }
                else
                    THM = abs(currPos) + abs(SORTED_ARRAY[x+1]-highestValue);
            }
            else
            {
                if(direction.equals("UPWARD"))
                {
                    THM = abs(currPos-highestValue) + abs(SORTED_ARRAY[x]);
                    DIRECTION = 1;
                }
                else
                    THM = abs(currPos) + abs(SORTED_ARRAY[x+1]-highestValue);
            }
            
            if( DIRECTION == 1 )
            {
                DIRECTION = 0;
                returnArray[0] = highestValue;
                returnArray[1] = 0;
                returnArray[2] = SORTED_ARRAY[x];
                for(int i=0;i<SORTED_ARRAY.length;i++)
                {
                    if(SORTED_ARRAY[i]>currPos&&SORTED_ARRAY[i]!=0)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                    
                }
                Output.append(Integer.toString(highestValue)+" ");
                Output.append(Integer.toString(0)+" ");
                for(int i=0;i<SORTED_ARRAY.length;i++)
                {
                    if(SORTED_ARRAY[i]<=currPos&&SORTED_ARRAY[i]!=0)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                    
                }
                
                
                
            }
            else
            {
                returnArray[0] = 0;
                returnArray[1] = highestValue;
                returnArray[2] = SORTED_ARRAY[x+1];
                for(int i=0;i<SORTED_ARRAY.length;i++)
                {
                    if(SORTED_ARRAY[i]<=currPos&&SORTED_ARRAY[i]!=0)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                    
                }
                Output.append(Integer.toString(0)+" ");
                Output.append(Integer.toString(highestValue)+" ");
                for(int i=0;i<SORTED_ARRAY.length;i++)
                {
                    if(SORTED_ARRAY[i]>currPos&&SORTED_ARRAY[i]!=0)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                    
                }
                
                
            }          
            

            DISPLAY += "Total Head Movement: " + THM + a_string + "\n\n";
            DISPLAY += "Seek Time:" + ST +"ms\n\n";
        }
        catch(Exception e)
        {
           e.printStackTrace();
        }
    }

    private void scanProcess() {
        try
        {
            int highestValue = Integer.parseInt(trackNoField.getText())-1;
            int prevPos = Integer.parseInt(prevPosField.getText());
            int currPos = Integer.parseInt(currPosField.getText());
            int lowestValue = 0;
            String direction = "";
            direction += dirComboBox.getSelectedItem();
            String a_string = "";
            DISPLAY = "SCAN\n\n";  

            if(prevPosField.isEnabled() == true)
            {
                if(prevPos<currPos)
                {
                    THM = abs(currPos-highestValue) + abs(highestValue-SORTED_ARRAY[0]);
                    DIRECTION = 1;
                }
                else
                {
                    THM = abs(currPos-0) + abs(SORTED_ARRAY[END-1]-0);
                }
                

            }
            else
            {
                if(direction.equals("UPWARD"))
                {
                    THM = abs(currPos-highestValue) + abs(highestValue-SORTED_ARRAY[0]);
                    DIRECTION = 1;
                }
                else
                    THM = abs(currPos-0) + abs(SORTED_ARRAY[END-1]-0);
            }
            
            if( DIRECTION == 1 )
            {
                returnArray[0]= highestValue;
                returnArray[1]= SORTED_ARRAY[0];
                DIRECTION = 0;
                for(int i=0;i<SORTED_ARRAY.length;i++)
                {
                    if(SORTED_ARRAY[i]>currPos)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                }
                Output.append(Integer.toString(highestValue)+" ");
                for(int i=SORTED_ARRAY.length-1;i>=0;i--)
                {
                    if(SORTED_ARRAY[i]<=currPos && SORTED_ARRAY[i]!=0)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                }


                
            }
            else
            {
                returnArray[0]= 0;
                returnArray[1]= SORTED_ARRAY[END-1];
                for(int i=SORTED_ARRAY.length-1;i>=0;i--)
                {
                    if(SORTED_ARRAY[i]<=currPos&&SORTED_ARRAY[i]!=0)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                }
                Output.append(Integer.toString(0)+" ");
                for(int i=0;i<SORTED_ARRAY.length;i++)
                {
                    if(SORTED_ARRAY[i]>currPos)
                    {
                        Output.append(Integer.toString(SORTED_ARRAY[i])+" ");
                    }
                }
            }
                
            
            DISPLAY += "Total Head Movement: " + THM + "\n\n";
            Output.append("\nTotal Head Movement: " + THM + "\n\n");
            DISPLAY += "Seek Time:" + ST +"ms\n\n";            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

 
    private void sstfProcess() {
        try
        {
            int prevPos = Integer.parseInt(prevPosField.getText());
            int currPos = Integer.parseInt(currPosField.getText());
            int upward_direction = 0;
            DISPLAY = "Shortest Seek Time First\n\n";
            int ctr = 0;
            
            if(prevPos<currPos)
                upward_direction= 1;
            
            int LOWER = 0;
            int HIGHER = 0;
            int MID = 0;
            int repeat = 0;
            int temp_MID = x;
            
            for(x = 1;x<END;x++)
            if((SORTED_ARRAY[x-1]<=currPos)&&(currPos<SORTED_ARRAY[x]))
            {    
                if(abs(currPos-SORTED_ARRAY[x-1])==abs(currPos-SORTED_ARRAY[x]))
                {
                    if(upward_direction==0)
                    {
                        LOWER = x-2;
                        MID = x-1;
                        HIGHER = x;
                        returnArray[ctr++] = SORTED_ARRAY[x-1];
                    }
                    else
                    {
                        LOWER = x-1;
                        MID = x;
                        HIGHER = x+1;
                        returnArray[ctr++] = SORTED_ARRAY[x];
                    }
                }
                else if(abs(currPos-SORTED_ARRAY[x-1])<abs(currPos-SORTED_ARRAY[x]))
                {
                    LOWER = x-2;
                    MID = x-1;
                    HIGHER = x;
                    returnArray[ctr++] = SORTED_ARRAY[x-1];
                }
                else
                {
                    LOWER = x-1;
                    MID = x;
                    HIGHER = x+1;
                    returnArray[ctr++] = SORTED_ARRAY[x];                    
                }
                break;
            }
            
                temp_MID = MID;
            
            while(ctr<END)
            {
                if((LOWER<0)||(HIGHER==END))
                {
                    if((LOWER<0)&&(HIGHER<END))
                    {
                        while(ctr<END)
                        {
                            returnArray[ctr++] = SORTED_ARRAY[HIGHER++];
                            if((repeat == 0)&&(HIGHER>=END))
                            {
                                returnArray[ctr++] = SORTED_ARRAY[END-1];
                                repeat = 1;
                            }
                        }
                    }
                    else if((HIGHER==END)&&(LOWER>=0))
                        while(ctr<END)
                        {
                            returnArray[ctr++] = SORTED_ARRAY[LOWER--];
                        }
                }
                else
                {
                   if(abs(SORTED_ARRAY[MID]-SORTED_ARRAY[LOWER])<abs(SORTED_ARRAY[MID]-SORTED_ARRAY[HIGHER]))
                   {
                       if((temp_MID==x)||(temp_MID == x-1))
                            returnArray[ctr++] = SORTED_ARRAY[LOWER];
                       else
                           returnArray[ctr++] = SORTED_ARRAY[MID];
                        MID = LOWER--;
                   }
                   else if(abs(SORTED_ARRAY[MID]-SORTED_ARRAY[LOWER])>abs(SORTED_ARRAY[MID]-SORTED_ARRAY[HIGHER]))
                   {
                        if((temp_MID==x)||(temp_MID == x-1))
                        {
                            returnArray[ctr++] = SORTED_ARRAY[HIGHER];
                            MID = HIGHER++;
                        }
                        else
                        {
                            returnArray[ctr++] = SORTED_ARRAY[MID];
                             MID = HIGHER++;
                        
                            if((repeat == 0)&&(HIGHER>=END))
                            {
                                returnArray[ctr++] = SORTED_ARRAY[END-1];
                                repeat = 1;
                            }        
                        }                
                   }
                   else if(abs(SORTED_ARRAY[MID]-SORTED_ARRAY[LOWER])==abs(SORTED_ARRAY[MID]-SORTED_ARRAY[HIGHER]))
                   {
                       if(upward_direction == 0)
                        {
                            if((temp_MID==x)||(temp_MID == x-1))
                                 returnArray[ctr++] = SORTED_ARRAY[LOWER];
                            else
                                returnArray[ctr++] = SORTED_ARRAY[MID];
                             MID = LOWER--;
                        }
                       else
                       {
                            if((temp_MID==x)||(temp_MID == x-1))
                            {
                                returnArray[ctr++] = SORTED_ARRAY[HIGHER];
                                MID = HIGHER++;
                            }
                            else
                            {
                                returnArray[ctr++] = SORTED_ARRAY[MID];
                                 MID = HIGHER++;

                                if((repeat == 0)&&(HIGHER>=END))
                                {
                                    returnArray[ctr++] = SORTED_ARRAY[END-1];
                                    repeat = 1;
                                }        
                            }  
                       }
                   }
                }
            }
            
            THM=abs(currPos-returnArray[0]);
            for(ctr=1;ctr<END;ctr++)
            {
                THM+=abs(returnArray[ctr-1]-returnArray[ctr]);
            }
            for(ctr=0;ctr<END;ctr++)
            {
                Output.append(Integer.toString(returnArray[ctr])+" ");
            }
            
            
            DISPLAY += "Total Head Movement: " + THM + "\n\n";
            Output.append("Total Head Movement: " + THM + "\n\n");
            DISPLAY += "Seek Time:" + ST +"ms\n\n";
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public static int returnArray(int a)
    { 
        return(returnArray[a]);   
    }

    public  int returnLimit()
    {
        int LIMIT = Integer.parseInt(trackNoField.getText());
        return LIMIT;
    }

    public static String returnDisplay()
    {
        return DISPLAY;
    }
    
    public static int returnArrayCount()
    {
        return END;
    }

    public  int returnCurrentPosition()
    {
        int currPos = Integer.parseInt(currPosField.getText());
        return currPos;
    }

    public  int returnPreviousPosition()
    {
        final int prevPos = Integer.parseInt(prevPosField.getText());
        return prevPos;
    }
    
    public  int returnChosenProcess()
    {
        if(fcfsBttn.isSelected()==true)
            return 1;
        else
        if(sstfBttn.isSelected()==true)
            return 2;   
        else
        if(scanBttn.isSelected()==true)
            return 3;   
        else
            return 5;
    }
}   

